### ISSUE TITLE
爬虫时出现异常：json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by LeeJiangWei** [DA1YAYUAN/JD-comments-sentiment-analysis#2]
你好，在运行jd_comment.py时出现如下错误：
```
> python jd_comment.py
Please enter the address:https://item.jd.com/100014870874.html
Traceback (most recent call last):
  File "jd_comment.py", line 115, in <module>
    batch_spider_comment()
  File "jd_comment.py", line 64, in batch_spider_comment
    spider_comment(i,key)
  File "jd_comment.py", line 41, in spider_comment
    r_json_obj = json.loads(r_json_str)
  File "C:\Users\anaconda3\envs\ir\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\anaconda3\envs\ir\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\anaconda3\envs\ir\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
请问是什么问题？

**Comment by DA1YAYUAN** [comment]
应该是没爬取到
检查一下你的代码开头的url变量是否和我现在的一样，之后修改过一版
不行的话再看下kv里面存的请求头是否改成了你自己浏览器的请求头

**Comment by LeeJiangWei** [comment]
> 检查一下你的代码开头的url变量是否和我现在的一样，之后修改过一版
> 不行的话再看下kv里面存的请求头是否改成了你自己浏览器的请求头

前几天才clone下来，url变量是一样的，header不知道如何修改？

**Comment by DA1YAYUAN** [comment]
把kv里面user-agent改成自己的试试
查看浏览器请求头具体方法可以百度

**Comment by LeeJiangWei** [comment]
更换user-agent后爬虫已经能正常工作，谢谢！
另外建议`open()`函数统一一下编码，代码里有一些指定了utf8有一些没有，运行的时候出现了点小问题。

**Comment by DA1YAYUAN** [comment]
> 更换user-agent后爬虫已经能正常工作，谢谢！
> 另外建议`open()`函数统一一下编码，代码里有一些指定了utf8有一些没有，运行的时候出现了点小问题。

好的，谢谢建议！
